# Uncomment this line to define a global platform for your project

source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '8.0'

target 'O365-iOS-Connect' do

pod 'ADALiOS'
pod 'Office365/Outlook'
pod 'Office365/Discovery'

end




